name: basic
description: A basic game built in Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.0.0

dependencies:
  audioplayers: ^5.2.0
  build_runner: ^2.4.13
  charts_flutter: ^0.12.0
  cloud_firestore: ^5.4.4
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.6
  device_info_plus: ^11.1.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  flutter:
    sdk: flutter
  gap: ^3.0.1
  go_router: ^13.0.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: ^1.2.2
  logging: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/avatar/
    - assets/images/
    - assets/music/
    - assets/sfx/
    - assets/words/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon-adaptive-foreground.png"
